### ISSUE TITLE
rustic-0.6.0 fails building on OpenBSD

### ISSUE THREAD

**Issue by bket** [rustic-rs/rustic#917]
rustic-0.6.0 fails to build on OpenBSD current using rust-1.73.0 with the error below. Issue seems to occur in rustic-core.

```
error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:666:38
    |
666 |             .map_err(LocalErrorKind::FromErrnoError)?;
    |                                      ^^^^^^^^^^^^^^
    |                                      |
    |                                      variant or associated item not found in `LocalErrorKind`
    |                                      help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:706:38
    |
706 |             .map_err(LocalErrorKind::FromErrnoError)?;
    |                                      ^^^^^^^^^^^^^^
    |                                      |
    |                                      variant or associated item not found in `LocalErrorKind`
    |                                      help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

error[E0599]: no variant or associated item named `SettingFilePermissionsFailed` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:749:42
    |
749 |                 .map_err(LocalErrorKind::SettingFilePermissionsFailed)?;
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ variant or associated item not found in `LocalErrorKind`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `SettingFilePermissionsFailed` not found for this enum

error[E0599]: no variant named `SymlinkingFailed` found for enum `LocalErrorKind`
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:918:78
    |
918 |                 symlink(linktarget, &filename).map_err(|err| LocalErrorKind::SymlinkingFailed {
    |                                                                              ^^^^^^^^^^^^^^^^ variant not found in `LocalErrorKind`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant `SymlinkingFailed` not found here

error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:936:46
    |
936 |                     .map_err(LocalErrorKind::FromErrnoError)?;
    |                                              ^^^^^^^^^^^^^^
    |                                              |
    |                                              variant or associated item not found in `LocalErrorKind`
    |                                              help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:950:46
    |
950 |                     .map_err(LocalErrorKind::FromErrnoError)?;
    |                                              ^^^^^^^^^^^^^^
    |                                              |
    |                                              variant or associated item not found in `LocalErrorKind`
    |                                              help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:954:46
    |
954 |                     .map_err(LocalErrorKind::FromErrnoError)?;
    |                                              ^^^^^^^^^^^^^^
    |                                              |
    |                                              variant or associated item not found in `LocalErrorKind`
    |                                              help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

error[E0599]: no variant or associated item named `FromErrnoError` found for enum `LocalErrorKind` in the current scope
   --> /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/backend/local.rs:958:46
    |
958 |                     .map_err(LocalErrorKind::FromErrnoError)?;
    |                                              ^^^^^^^^^^^^^^
    |                                              |
    |                                              variant or associated item not found in `LocalErrorKind`
    |                                              help: there is a variant with a similar name: `FromTryIntError`
    |
   ::: /tmp/pobj/rustic-0.6.0/rustic-0.6.0/modcargo-crates/rustic_core-0.1.1/src/error.rs:598:1
    |
598 | pub enum LocalErrorKind {
    | ----------------------- variant or associated item `FromErrnoError` not found for this enum

For more information about this error, try `rustc --explain E0599`.                                                                                                     
error: could not compile `rustic_core` (lib) due to 8 previous errors
```

**Comment by aawsome** [comment]
Thanks a lot for reporting and sorry for the inconvenience. Damn - this is the problem of not being able to cross-compile to openbsd on github actions :-(

**Comment by bket** [comment]
Issue indeed occurs in rustic_core, and needs to be resolved there. A PR has been opened (https://github.com/rustic-rs/rustic_core/pull/28). I'm closing this issue here.
